version: '3'
networks:
  kafka-logstash-spark-collector:
    external: true

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /var/lib/minio-data
    ports:
      - 29010:9000
      - 29011:9001
    volumes:
      - ./minio-data:/var/lib/minio-data
    environment:
      MINIO_ROOT_USER: minio-root
      MINIO_ROOT_PASSWORD: MyStr0n8Passw04rd*
    networks:
      - kafka-logstash-spark-collector

  createbuckets:
    image: minio/mc
    container_name: init-bucket-minio
    networks:
      - kafka-logstash-spark-collector
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio-root MyStr0n8Passw04rd*;
      /usr/bin/mc mb myminio/flights-enriched;
      /usr/bin/mc policy set public myminio/flights-enriched;
      exit 0;
      "
