tags: ["flightradar"]
name: "flightradar-filebeat"
max_procs: 4

filebeat.inputs:
  - type: filestream
    id: flightradar-fb
    enabled: true
    json.keys_under_root: true
    json.add_error_key: true
    paths: 
      - /usr/share/services/node/*.json

output.kafka:
  version: 2.6.0
  hosts: ["broker:29092"]
  topic: 'flights'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
