version: "3.7"
networks:
  kafka-logstash-spark-collector:
    external: true

services:
  collector:
    container_name: collector
    image: anghille/collector:0.1.0
    pull_policy: always
    restart: unless-stopped
    volumes:
      - ./collector/input/:/input/
    networks:
      - kafka-logstash-spark-collector
