version: "3.7"
networks:
  kafka-logstash-spark-collector:
    external: true

services:
  collector:
    container_name: collector
    image: anghille/test
    pull_policy: always
    restart: unless-stopped
    volumes:
      - ./collector/input/flight_data.json:/input/flight_data.json
    networks:
      - kafka-logstash-spark-collector
